var
        a,b,c:longint;
        s:real;
begin
        assign(input,'score.in');reset(input);
        assign(output,'score.out');rewrite(output);
        readln(a,b,c);
        s:=a*0.2+b*0.3+c*0.5;
        writeln(s:0:0);
        close(input);close(output);
end.