var
a,s,b,c:integer;
begin
assign(input,'score.in');
assign(output,'score.out');
reset(input);
rewrite(output);
 read(a,b,c);
 s:=trunc(a*0.2+b*0.3+c*0.5);
 write(s);
close(input);
close(output);
end.
