var
        i,j,k,x,y,z,ls:longint;
        s:extended;
begin
        assign(input,'score.in');
        reset(input);
        assign(output,'score.out');
        rewrite(output);
        readln(x,y,z);
        s:=x*0.2+y*0.3+z*0.5;
        writeln(s:0:0);
        close(input);
        close(output);
end.