var
 j,k,l:longint;
 i:real;
begin
 assign(input,'score.in');reset(input);
 assign(output,'score.out');rewrite(output);
 readln(j,k,l);
 i:=j*0.2+k*0.3+l*0.5;
 write(i:0:0);
 close(input);close(output);
end.
